Update docs for Qubes 4.1
Made sure to test in dom0 on 4.1. The "disablerepo" flag was necessary
on my recently-migrated machine. Might be overkill, but including for
clarity since it won't do any harm.

The madness about /usr/{local,}/bin/hexagon path in the rpm seems
to be related to whether a virtualenv was used for building. Mea culpa.
On Debian 11 Bullseye, with NO virtualenv, the /usr/local/bin/ path is
used. I can't seem to find good documentation on this behavior,
so I'm letting it flap.

diff --git a/scripts/build-dom0-rpm b/scripts/build-dom0-rpm
--- a/scripts/build-dom0-rpm
+++ b/scripts/build-dom0-rpm
@@ -5,6 +5,12 @@ set -e
 set -u
 set -o pipefail
 
+
+if [[ -n "${VIRTUAL_ENV:-}" ]]; then
+    echo "ERROR: unset VIRTUAL_ENV. Using a virtualenv interferes with package reproducibility."
+    exit 1
+fi
+
 # Prepare tarball, rpmbuild will use it
 mkdir -p dist/
 rm -f dist/*.tar.gz
