build: super simple rpm
Leans into the reproducible builds provided via nxi
to emit a single RPM artifact, regardless of target Qubes version.
The program doesn't use any pip-installable dependencies; the only
Python deps are provided by Qubes dom0 RPM packages.

Requires a path hack, but that's tolerable for the simplicity.

diff --git a/scripts/install-rpm b/scripts/install-rpm
--- a/scripts/install-rpm
+++ b/scripts/install-rpm
@@ -1,31 +1,15 @@
 #!/bin/bash
-# Installs locally built RPM in dom0.
-# Required for local builds.
+# Installs the locally built RPM in dom0. There's a single universal noarch
+# package (built by `just rpm` / `nix build .#rpm`), so just find it and install it.
 set -euo pipefail
 
 
-fedora_version="$(rpm --eval '%{fedora}')"
-
-
-pkg="$(find rpm-build/ -type f -iname "*fc${fedora_version}.noarch.rpm" | sort -V | tail -n1)"
+pkg="$(find rpm-build/RPMS/noarch -type f -iname '*.noarch.rpm' | sort -V | tail -n1)"
 if [[ -z $pkg ]]; then
-    echo "ERROR: No RPM found. Run 'make rpm' in the AppVM, then try again"
+    echo "ERROR: No RPM found. Run 'just rpm' in the AppVM, then try again." >&2
     exit 1
 fi
 
-if [[ $fedora_version = "25" ]]; then
-    echo "Installing RPM for Qubes 4.0, Fedora ${fedora_version}..."
-elif [[ $fedora_version = "32" ]]; then
-    echo "Installing RPM for Qubes 4.1, Fedora ${fedora_version}..."
-elif [[ $fedora_version = "37" ]]; then
-    echo "Installing RPM for Qubes 4.2, Fedora ${fedora_version}..."
-elif [[ $fedora_version = "42" ]]; then
-    echo "Installing RPM for Qubes 4.3, Fedora ${fedora_version}..."
-else
-    echo "ERROR: Unsupported Fedora version '${fedora_version}'"
-    exit 2
-fi
-
-# Disable "qubes-dom0-cached" repo to avoid problems with local rpm
-# installation on Qubes 4.1.
+echo "Installing ${pkg}..."
+# Disable "qubes-dom0-cached" repo to avoid problems with local rpm installation.
 sudo dnf --disablerepo=qubes-dom0-cached install -y "$pkg"
